name: amcare1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # GetX untuk state management & routing
  get: ^4.6.5
<<<<<<< HEAD
  url_launcher: ^6.2.2
  font_awesome_flutter: ^10.6.0
=======
>>>>>>> e0c14dc96216e9a64eda25ee6dde43e409100d6f

  # HTTP
  http: ^0.13.6

  # Barcode
  barcode_widget: ^2.0.4

  # iOS icons
  cupertino_icons: ^1.0.8

<<<<<<< HEAD
  # ⭐⭐⭐ Animasi Super Ringan & Keren
  flutter_staggered_animations: ^1.1.1
  
  # ⭐ Carousel animasi (opsional tapi bagus)
  carousel_slider: ^4.2.1

=======
  # Animasi Super Ringan & Keren
  flutter_staggered_animations: ^1.1.1
  
  # Carousel animasi
  carousel_slider: ^4.2.1

  # Telepon, WhatsApp, Browser
  url_launcher: ^6.2.4

  # Icon WhatsApp & Sirine
  font_awesome_flutter: ^10.7.0

  # Storage untuk token / session key
  get_storage: ^2.1.1

  # HTTP client modern
  dio: ^5.9.0
>>>>>>> e0c14dc96216e9a64eda25ee6dde43e409100d6f

dev_dependencies:
  flutter_test:
    sdk: flutter
<<<<<<< HEAD

=======
>>>>>>> e0c14dc96216e9a64eda25ee6dde43e409100d6f
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-SemiBold.ttf
          weight: 600

  assets:
    - assets/images/logo_rs.png
    - assets/images/pendaftaran.png
    - assets/images/rekam_medis.png
    - assets/images/antrian.png
    - assets/images/jadwal.png
    - assets/images/klinik.png
    - assets/images/tempat_tidur.png
    - assets/images/farmasi.png
    - assets/images/emergency.png
    - assets/images/promosi.png
    - assets/images/background-marble.png
<<<<<<< HEAD
=======
    - assets/images/akupunkture.png
    - assets/images/anak.png
    - assets/images/beautycenter.png
    - assets/images/bedah.png
    - assets/images/dokterumum.png
    - assets/images/fisioterapi.png
    - assets/images/gigi.png
    - assets/images/hipnoterapi.png
    - assets/images/jantung.png
    - assets/images/igd.png
    - assets/images/kulit.png
    - assets/images/laboratorium.png
    - assets/images/laktasi.png
    - assets/images/mata.png
    - assets/images/obgyn.png
    - assets/images/okupasi.png
    - assets/images/orthopedi.png
    - assets/images/ozon.png
    - assets/images/paru.png
    - assets/images/penyakit dalam b.png
    - assets/images/penyakitdalam.png
    - assets/images/psikiatri.png
    - assets/images/radiologi.png
    - assets/images/rehab_medik.png
    - assets/images/stemcell.png
    - assets/images/syaraf.png
    - assets/images/terapi_wicara.png
    - assets/images/THT.png
    - assets/images/vaksin.png
>>>>>>> e0c14dc96216e9a64eda25ee6dde43e409100d6f
